#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${PROJECT_ROOT}"

STAMP="$(date +%Y%m%d_%H%M%S)"
SAVE_PATH="${SAVE_PATH:-$PROJECT_ROOT/outputs/detector_stage1_vitdet_1024_lsj01_20_${STAMP}}"

sbatch \
  --export="ALL,SAVE_PATH=${SAVE_PATH},BACKBONE=${BACKBONE:-vitdet},VIT_INPUT_SIZE=${VIT_INPUT_SIZE:-1024},VIT_LSJ_MIN_SCALE=${VIT_LSJ_MIN_SCALE:-0.1},VIT_LSJ_MAX_SCALE=${VIT_LSJ_MAX_SCALE:-2.0},VITDET_FREEZE=${VITDET_FREEZE:-0},NEPOCH=${NEPOCH:-8},MAX_TRAIN_STEPS=${MAX_TRAIN_STEPS:--1},MAP_MAX_STEPS=${MAP_MAX_STEPS:--1},MAP_MAX_VIDEO_FRAMES=${MAP_MAX_VIDEO_FRAMES:--1},PATIENCE=${PATIENCE:-3},EVAL_EVERY=${EVAL_EVERY:-1},LOG_EVERY=${LOG_EVERY:-100},BATCH_SIZE=${BATCH_SIZE:-1},NUM_WORKERS=${NUM_WORKERS:-2},EVAL_NUM_WORKERS=${EVAL_NUM_WORKERS:-0},VITDET_DET_CHUNK=${VITDET_DET_CHUNK:-1},VIT_LR=${VIT_LR:-5e-6},HEAD_LR=${HEAD_LR:-1e-4},DETECTOR_REINIT_ROI_HEADS=${DETECTOR_REINIT_ROI_HEADS:-1},DETECTOR_SKIP_AG_HEAD_LOAD=${DETECTOR_SKIP_AG_HEAD_LOAD:-1},DETECTOR_BN_MODE=${DETECTOR_BN_MODE:-groupnorm}" \
  "scripts/train_detector_stage1_h100.sbatch"
