#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${PROJECT_ROOT}"

STAMP="$(date +%Y%m%d_%H%M%S)"
SAVE_PATH="${SAVE_PATH:-$PROJECT_ROOT/outputs/sttran_sgdet_vitdet_stage2_nonmae_best_${STAMP}}"
DETECTOR_CKPT="${DETECTOR_CKPT:-$PROJECT_ROOT/outputs/detector_stage1_vitdet_1024_lsj05_20_full_b8_resume_condo7_20260416_131510/detector_stage1_best.pth}"

SBATCH_ARGS=("$@")

sbatch \
  "${SBATCH_ARGS[@]}" \
  --export="ALL,DATA_PATH=${DATA_PATH:-$HOME/special_topics/datasets/action_genome},MODE=${MODE:-sgdet},DATASIZE=${DATASIZE:-large},SAVE_PATH=${SAVE_PATH},NEPOCH=${NEPOCH:-10},LR=${LR:-1e-6},ENC_LAYER=${ENC_LAYER:-1},DEC_LAYER=${DEC_LAYER:-3},OPTIMIZER=${OPTIMIZER:-adamw},BCE_LOSS=${BCE_LOSS:-0},BACKBONE=${BACKBONE:-vitdet},DET_THRESHOLD=${DET_THRESHOLD:-0.1},CKPT=${CKPT:-},DETECTOR_CKPT=${DETECTOR_CKPT},TRAIN_DETECTOR=${TRAIN_DETECTOR:-1},TWO_STAGE=${TWO_STAGE:-1},STAGE1_EPOCHS=${STAGE1_EPOCHS:-0},RUN_EVAL=${RUN_EVAL:-1},EVAL_EVERY=${EVAL_EVERY:-1},CKPT_EVERY=${CKPT_EVERY:-1},LOG_EVERY=${LOG_EVERY:-100},NUM_WORKERS=${NUM_WORKERS:-4},EVAL_NUM_WORKERS=${EVAL_NUM_WORKERS:-2},MAX_VIDEO_FRAMES=${MAX_VIDEO_FRAMES:-24},VITDET_DET_CHUNK=${VITDET_DET_CHUNK:-4},VITDET_MODEL=${VITDET_MODEL:-vit_base_patch16_224},VIT_INPUT_SIZE=${VIT_INPUT_SIZE:-1024},DETECTOR_LOAD_AG_CKPT=${DETECTOR_LOAD_AG_CKPT:-0},DETECTOR_SKIP_AG_HEAD_LOAD=${DETECTOR_SKIP_AG_HEAD_LOAD:-0},DETECTOR_REINIT_ROI_HEADS=${DETECTOR_REINIT_ROI_HEADS:-0},DETECTOR_BN_MODE=${DETECTOR_BN_MODE:-groupnorm},VIT_LR=${VIT_LR:-5e-6},TASK_LR=${TASK_LR:-1e-4},WEIGHT_DECAY=${WEIGHT_DECAY:-1e-4},STAGE2_TASK_LR=${STAGE2_TASK_LR:-1e-4},STAGE2_VIT_LR=${STAGE2_VIT_LR:-5e-6},STAGE2_WEIGHT_DECAY=${STAGE2_WEIGHT_DECAY:-1e-4},STAGE2_UNFREEZE_LAST_VIT_BLOCK=${STAGE2_UNFREEZE_LAST_VIT_BLOCK:-0}" \
  "scripts/train_sttran_h100.sbatch"
